<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>SPT-VR</AssemblyName>
	  <Description>VR mod for Single Player Tarkov</Description>
	  <Version>1.0.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
    <RootNamespace>TarkovVR</RootNamespace>
    <UserSecretsId>a5566ab9-7cd4-4d4a-9f17-1401464a5e66</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ModSupport\EFTApiSupport.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="TAA.shader" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.*" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
    <PackageReference Include="UnityEngine.Modules" Version="2019.4.39" IncludeAssets="compile" />
  </ItemGroup>
  
  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
  </ItemGroup>
  
  <ItemGroup>
    <Reference Include="Aki.Reflection">
      <HintPath>libs\Aki.Reflection.dll</HintPath>
    </Reference>
    <Reference Include="AmandsGraphics">
      <HintPath>libs\ModSupport\AmandsGraphics.dll</HintPath>
    </Reference>
    <Reference Include="AnimationSystem.Types">
      <HintPath>libs\Managed\AnimationSystem.Types.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>libs\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>libs\Managed\Assembly-CSharp-firstpass.dll</HintPath>
    </Reference>
    <Reference Include="Cinemachine">
      <HintPath>libs\Managed\Cinemachine.dll</HintPath>
    </Reference>
    <Reference Include="Comfort">
      <HintPath>libs\Managed\Comfort.dll</HintPath>
    </Reference>
    <Reference Include="Comfort.Unity">
      <HintPath>libs\Managed\Comfort.Unity.dll</HintPath>
    </Reference>
    <Reference Include="CommonExtensions">
      <HintPath>libs\Managed\CommonExtensions.dll</HintPath>
    </Reference>
    <Reference Include="EFTConfiguration">
      <HintPath>libs\ModSupport\KmyTarkovConfiguration.dll</HintPath>
    </Reference>
    <Reference Include="Fika.Core">
      <HintPath>libs\ModSupport\Fika.Core.dll</HintPath>
    </Reference>
    <Reference Include="FIKAVRSync">
      <HintPath>libs\ModSupport\FIKAVRSync.dll</HintPath>
    </Reference>
    <Reference Include="ItemComponent.Types">
      <HintPath>libs\Managed\ItemComponent.Types.dll</HintPath>
    </Reference>
    <Reference Include="KmyTarkovConfiguration">
      <HintPath>C:\Users\lilma\Downloads\SPT-VR-main\SPT-VR-main\libs\ModSupport\KmyTarkovConfiguration.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.CSharp">
      <HintPath>C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\Microsoft.CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>libs\Managed\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="Sirenix.Serialization">
      <HintPath>libs\Managed\Sirenix.Serialization.dll</HintPath>
    </Reference>
    <Reference Include="SteamVR">
      <HintPath>libs\Managed\SteamVR.dll</HintPath>
    </Reference>
    <Reference Include="SteamVR_Actions">
      <HintPath>libs\Managed\SteamVR_Actions.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Postprocessing.Runtime">
      <HintPath>libs\Managed\Unity.Postprocessing.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>libs\Managed\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="Unity.XR.Management">
      <HintPath>libs\Managed\Unity.XR.Management.dll</HintPath>
    </Reference>
    <Reference Include="Unity.XR.OpenVR">
      <HintPath>libs\Managed\Unity.XR.OpenVR.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>libs\Managed\UnityEngine.UI.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
